version: 1.0

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bloomup
      POSTGRES_PASSWORD: bloomup_pw
      POSTGRES_DB: bloomup_dev
    volumes:
      - db_data:/var/lib/postgresql/data


  api:
    image: chassss/bloomup-api:latest
    env_file:
      - ./backend/.env 
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro

  web:
    image: chassss/bloomup-web:latest
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  # DB GUI (visit http://127.0.0.1:5051)
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
