name: Frontend ESLint

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/eslint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

concurrency:
  group: eslint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint --if-present || echo "No lint script found"

      - name: Check code formatting (Prettier)
        working-directory: frontend
        run: npm run format:check --if-present || echo "No format:check script found"

  typescript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Type check with TypeScript
        working-directory: frontend
        run: npx tsc --noEmit || echo "No TypeScript config found"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Next.js
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:8000"
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: frontend/.next
          retention-days: 1
          